const fs = require('fs');
const path = 'c:/Users/FLEX/approximatelvl-simulator/src/SimulationEngine.js';
let text = fs.readFileSync(path, 'latin1');

text = text.replace('  const valuesToSend = algorithm === "MIN" && originalValues ? originalValues : values;\r\n  \r\n', '  const valuesToSend = algorithm === "MIN" && originalValues ? originalValues : values;\r\n  const senderCoupledDelivery = algorithm === "COURTEOUS COUPLED";\r\n  \r\n');
text = text.replace('    const deliveryStatus = [];\r\n    \r\n', '    const deliveryStatus = [];\r\n    const senderDeliveryOutcome = senderCoupledDelivery ? randomDecimal().lte(decP) : null;\r\n    \r\n');
text = text.replace('        const delivered = randomDecimal().lte(decP);', '        const delivered = senderCoupledDelivery ? senderDeliveryOutcome : randomDecimal().lte(decP);');
text = text.replace('["COURTEOUS", "SELFISH", "CYCLIC", "BIASED0"]', '["COURTEOUS", "COURTEOUS COUPLED", "SELFISH", "CYCLIC", "BIASED0"]');
text = text.replace('      if (algorithm === "COURTEOUS") {', '      if (algorithm === "COURTEOUS" || algorithm === "COURTEOUS COUPLED") {');
text = text.replace('      } else if (algorithm === "COURTEOUS") {\r\n        // Ecuación teórica para COURTEOUS (solo válida para 3 procesos)\r\n        const pNum = decP.toNumber();\r\n        const singleRoundDiscrepancy = 1 - 2*pNum + 4*Math.pow(pNum, 2) - 4*Math.pow(pNum, 3) + Math.pow(pNum, 4);\r\n        return Math.pow(singleRoundDiscrepancy, rounds);\r\n      } else {', '      } else if (algorithm === "COURTEOUS") {\r\n        // Ecuación teórica para COURTEOUS (solo válida para 3 procesos)\r\n        const pNum = decP.toNumber();\r\n        const singleRoundDiscrepancy = 1 - 2*pNum + 4*Math.pow(pNum, 2) - 4*Math.pow(pNum, 3) + Math.pow(pNum, 4);\r\n        return Math.pow(singleRoundDiscrepancy, rounds);\r\n      } else if (algorithm === "COURTEOUS COUPLED") {\r\n        return null;\r\n      } else {');
text = text.replace('    if (algorithm === "COURTEOUS") {\r\n      const pNum = decP.toNumber();\r\n      const singleRoundFactor = 1 - 2*pNum + 4*Math.pow(pNum, 2) - 4*Math.pow(pNum, 3) + Math.pow(pNum, 4);\r\n      return Math.pow(singleRoundFactor, rounds);\r\n    }\r\n\r\n    if (algorithm === "AMP") {', '    if (algorithm === "COURTEOUS") {\r\n      const pNum = decP.toNumber();\r\n      const singleRoundFactor = 1 - 2*pNum + 4*Math.pow(pNum, 2) - 4*Math.pow(pNum, 3) + Math.pow(pNum, 4);\r\n      return Math.pow(singleRoundFactor, rounds);\r\n    }\r\n\r\n    if (algorithm === "COURTEOUS COUPLED") {\r\n      return null;\r\n    }\r\n\r\n    if (algorithm === "AMP") {');
text = text.replace('    let singleRoundFactor;\r\n    if (algorithm === "AMP") {', '    let singleRoundFactor;\r\n    if (algorithm === "COURTEOUS COUPLED") {\r\n      return null;\r\n    }\r\n    if (algorithm === "AMP") {');
text = text.replace('    let singleRoundFactor;\r\n\r\n    if (algorithm === "AMP") {', '    let singleRoundFactor;\r\n\r\n    if (algorithm === "COURTEOUS COUPLED") {\r\n      return null;\r\n    }\r\n\r\n    if (algorithm === "AMP") {');
text = text.replace('      case "COURTEOUS":\r\n        // Ecuación teórica EXACTA del paper para Courteous\r\n        return 1 - 2*p + 4*Math.pow(p, 2) - 4*Math.pow(p, 3) + Math.pow(p, 4);\r\n        \r\n      case "SELFISH":', '      case "COURTEOUS":\r\n        // Ecuación teórica EXACTA del paper para Courteous\r\n        return 1 - 2*p + 4*Math.pow(p, 2) - 4*Math.pow(p, 3) + Math.pow(p, 4);\r\n        \r\n      case "COURTEOUS COUPLED":\r\n        return null;\r\n        \r\n      case "SELFISH":');
fs.writeFileSync(path, text, 'latin1');
